version: '2.2'
services:
  postgres:
    image: postgres:12.5-alpine
    ports:
      - '${DB_CONTAINER_PORT}:5432'
    volumes:
      - ${DB_DIR}:/var/lib/postgresql/data
      - ./ltreeInit.sql:/docker-entrypoint-initdb.d/ltreeInit.sql
      - ./regionsTableInit.sql:/docker-entrypoint-initdb.d/regionsTableInit.sql
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_STATIC_FILES_LOCATION}:/etc/nginx/html:ro
    ports:
      - '${NGINX_PORT}:80'
    restart: always

  regions-api-server:
    build:
      context: ./regions-api-server
      args:
        mode: ${MODE}
    restart: always
    environment:
      - DB_URL=postgres://${DB_USERNAME}:${DB_PASS}@postgres:${DB_CONTAINER_PORT}/${DB_NAME}
      - DB_TABLE_NAME
      - PORT
      - NODE_ENV=${MODE}
    depends_on:
      - postgres
